// <copyright file="PostShippingClaimUpdate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>8/3/2016 11:18:59 AM</date>
// <summary>Implements the PostShippingClaimUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.ShippingClaim;
    using GSC.Rover.DMS.BusinessLogic.Common;
    using Microsoft.Xrm.Sdk.Query;

    /// <summary>
    /// PostShippingClaimUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostShippingClaimUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// </summary>
        private readonly string preImageAlias = "PreImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostShippingClaimUpdate"/> class.
        /// </summary>
        public PostShippingClaimUpdate()
            : base(typeof(PostShippingClaimUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_sls_shippingclaim", new Action<LocalPluginContext>(ExecutePostShippingClaimUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostShippingClaimUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            Entity shippingClaimEntity = (Entity)context.InputParameters["Target"];

            if (!(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)) { return; }

            if (shippingClaimEntity.LogicalName != "gsc_sls_shippingclaim") { return; }

            if (context.Mode == 0) //Synchronous Plug-in
            {
                string message = context.MessageName;

                try
                {
                    #region Pre-images
                    Guid preImageReceivingTransaction = preImageEntity.GetAttributeValue<EntityReference>("gsc_receivingtransactionid") != null
                        ? preImageEntity.GetAttributeValue<EntityReference>("gsc_receivingtransactionid").Id
                        : Guid.Empty;
                    
                    Int32 preImageScrStatus = preImageEntity.GetAttributeValue<OptionSetValue>("gsc_scrstatus") != null
                        ? preImageEntity.GetAttributeValue<OptionSetValue>("gsc_scrstatus").Value
                        : 0;
                    #endregion

                    #region Post-images
                    Guid postImageReceivingTransaction = postImageEntity.GetAttributeValue<EntityReference>("gsc_receivingtransactionid") != null
                        ? postImageEntity.GetAttributeValue<EntityReference>("gsc_receivingtransactionid").Id
                        : Guid.Empty;

                    Int32 postImageScrStatus = postImageEntity.GetAttributeValue<OptionSetValue>("gsc_scrstatus") != null
                        ? postImageEntity.GetAttributeValue<OptionSetValue>("gsc_scrstatus").Value
                        : 0;
                    #endregion

                    ShippingClaimHandler shippingClaimHandler = new ShippingClaimHandler(service, trace);

                    //Functions on Invoice No change
                    if (preImageReceivingTransaction != postImageReceivingTransaction)
                    {
                        shippingClaimHandler.DeleteExistingShippingClaimDetail(postImageEntity);
                        shippingClaimHandler.ReplicateReceivingTransactionFields(postImageEntity, message);
                    }

                    //Functions on SCR Status change
                    if (preImageScrStatus != postImageScrStatus)
                    {
                        //Trigger function on 'PostImageScrStatus == Cancelled'
                        if (postImageScrStatus == 100000003)
                        {
                            shippingClaimHandler.AdjustCancelledOpenInventoryMovement(preImageEntity);
                            shippingClaimHandler.AdjustCancelledSubmittedInventoryMovement(preImageEntity);                            
                        }
                        
                        shippingClaimHandler.AdjustSubmittedInventoryMovement(postImageEntity);
                        shippingClaimHandler.AdjustRepairedInventoryMovement(postImageEntity);
                    }
                }
                catch (Exception ex)
                {
                    //throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace, Environment.NewLine, error));
                    throw new InvalidPluginExecutionException(ex.Message);
                }
            }
        }
    }
}
