// <copyright file="PostVehiclePostDeliveryMonitoringUpdate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>6/3/2016 2:07:07 PM</date>
// <summary>Implements the PostVehiclePostDeliveryMonitoringUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.VehiclePostDeliveryMonitoring;

    /// <summary>
    /// PostVehiclePostDeliveryMonitoringUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostVehiclePostDeliveryMonitoringUpdate : Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// </summary>
        private readonly string preImageAlias = "PreImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostVehiclePostDeliveryMonitoringUpdate"/> class.
        /// </summary>
        public PostVehiclePostDeliveryMonitoringUpdate()
            : base(typeof(PostVehiclePostDeliveryMonitoringUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_sls_vehiclepostdeliverymonitoring", new Action<LocalPluginContext>(ExecutePostVehiclePostDeliveryMonitoringUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostVehiclePostDeliveryMonitoringUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            Entity vehiclePostDeliveryMonitoring = (Entity)context.InputParameters["Target"];

            if (!(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)) { return; }

            if (vehiclePostDeliveryMonitoring.LogicalName != "gsc_sls_vehiclepostdeliverymonitoring") { return; }

            if (context.Mode == 0) //Synchronous Plug-in
            {
                string message = context.MessageName;

                try
                {
                    #region Pre-images

                    var preImageSurveySetup = preImageEntity.GetAttributeValue<EntityReference>("gsc_surveysetupid") != null
                        ? preImageEntity.GetAttributeValue<EntityReference>("gsc_surveysetupid").Id
                        : Guid.Empty;

                    var preImageCompleted = preImageEntity.GetAttributeValue<Boolean>("gsc_completed");

                    #endregion

                    #region Post-images

                    var postImageSurveySetup = postImageEntity.GetAttributeValue<EntityReference>("gsc_surveysetupid") != null
                        ? postImageEntity.GetAttributeValue<EntityReference>("gsc_surveysetupid").Id
                        : Guid.Empty;

                    var postImageCompleted = postImageEntity.GetAttributeValue<Boolean>("gsc_completed");

                    #endregion

                    VehiclePostDeliveryMonitoringHandler vehiclePostDeliveryMonitoringHandler = new VehiclePostDeliveryMonitoringHandler(service, trace);

                    if (preImageSurveySetup != postImageSurveySetup)
                    {
                        vehiclePostDeliveryMonitoringHandler.DeleteExistingSurveyQuestions(postImageEntity);
                    }

                    if (preImageCompleted != postImageCompleted)
                    {
                        vehiclePostDeliveryMonitoringHandler.ValidateSurveyQuestions(postImageEntity);
                        vehiclePostDeliveryMonitoringHandler.UpdateStatusAndCallDate(postImageEntity);
                    }
                }
                catch (Exception ex)
                {
                    if (ex.Message.Contains("Survey has no answer."))
                    {
                        throw new InvalidPluginExecutionException("Please complete the survey provided.");
                    }
                    else
                    {
                        throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace));
                    }                    
                }
            }
        }
    }
}
