// <copyright file="PostVehicleInTransitTransferReceivingUpdate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>9/1/2016 1:52:00 PM</date>
// <summary>Implements the PostVehicleInTransitTransferReceivingUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.VehicleInTransitTransferReceiving;

    /// <summary>
    /// PostVehicleInTransitTransferReceivingUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostVehicleInTransitTransferReceivingUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// </summary>
        private readonly string preImageAlias = "PreImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostVehicleInTransitTransferReceivingUpdate"/> class.
        /// </summary>
        public PostVehicleInTransitTransferReceivingUpdate()
            : base(typeof(PostVehicleInTransitTransferReceivingUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_iv_vehicleintransittransferreceiving", new Action<LocalPluginContext>(ExecutePostVehicleInTransitTransferReceivingUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostVehicleInTransitTransferReceivingUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            Entity vehicleTransitReceiving = (Entity)context.InputParameters["Target"];

            if (!(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)) { return; }

            if (vehicleTransitReceiving.LogicalName != "gsc_iv_vehicleintransittransferreceiving") { return; }

            if (context.Mode == 0) //Synchronous Plug-in
            {
                try
                {
                    var preStatus = preImageEntity.Contains("gsc_intransitstatus") ? preImageEntity.GetAttributeValue<OptionSetValue>("gsc_intransitstatus").Value
                        : 0;

                    var postStatus = postImageEntity.Contains("gsc_intransitstatus") ? postImageEntity.GetAttributeValue<OptionSetValue>("gsc_intransitstatus").Value
                        : 0;
 
                    VehicleInTransitTransferReceivingHandler vehicleReceivingHandler = new VehicleInTransitTransferReceivingHandler(service, trace);

                    //BL for postStatus changed to Received
                    if (preStatus != postStatus && postStatus == 100000001)
                    {
                        vehicleReceivingHandler.ReceiveTransfer(preImageEntity);
                    }
                    else if (preStatus != postStatus && postStatus == 100000002)
                    {
                        vehicleReceivingHandler.CancelTransfer(preImageEntity);
                    }
                }

                catch (Exception ex)
                {
                    throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace));
                }
            }
        }
    }
}
