// <copyright file="PostReturnTransactionUpdate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>7/18/2016 5:52:51 PM</date>
// <summary>Implements the PostReturnTransactionUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.ReturnTransaction;

    /// <summary>
    /// PostReturnTransactionUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostReturnTransactionUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// </summary>
        private readonly string preImageAlias = "PreImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostReturnTransactionUpdate"/> class.
        /// </summary>
        public PostReturnTransactionUpdate()
            : base(typeof(PostReturnTransactionUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_cmn_returntransaction", new Action<LocalPluginContext>(ExecutePostReturnTransactionUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostReturnTransactionUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;

            if (!(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)) { return; }

            Entity documentChecklistEntity = (Entity)context.InputParameters["Target"];

            if (documentChecklistEntity.LogicalName != "gsc_cmn_returntransaction") { return; }

            if (context.Mode == 0) //synchronous plugin
            {
                try
                {
                    var preReturnStatus = preImageEntity.Contains("gsc_returnstatus") ? preImageEntity.GetAttributeValue<OptionSetValue>("gsc_returnstatus").Value
                        : 0;
                    var preReceivingTransactionId = preImageEntity.Contains("gsc_receivingtransactionid") ? preImageEntity.GetAttributeValue<EntityReference>("gsc_receivingtransactionid").Id
                        : Guid.Empty;
                    var preVrStatus = preImageEntity.Contains("gsc_vrstatus") ? preImageEntity.GetAttributeValue<OptionSetValue>("gsc_vrstatus").Value
                        : 0;

                    var postReturnStatus = postImageEntity.Contains("gsc_returnstatus") ? postImageEntity.GetAttributeValue<OptionSetValue>("gsc_returnstatus").Value
                        : 0;
                    var postReceivingTransactionId = postImageEntity.Contains("gsc_receivingtransactionid") ? postImageEntity.GetAttributeValue<EntityReference>("gsc_receivingtransactionid").Id
                        : Guid.Empty;
                    var postVrStatus = postImageEntity.Contains("gsc_vrstatus") ? postImageEntity.GetAttributeValue<OptionSetValue>("gsc_vrstatus").Value
                        : 0;


                    ReturnTransactionHandler returnTransactionHandler = new ReturnTransactionHandler(service, trace);

                    //receiving transaction id changed
                    if (preReceivingTransactionId != postReceivingTransactionId)
                    {
                        returnTransactionHandler.PopulateReturnTransactionFields(postImageEntity);
                        returnTransactionHandler.AdjustProductQuantity(postImageEntity, "allocate");
                    }

                    //return status changed
                    if (preReturnStatus != postReturnStatus)
                    { 
                        //status set to returned
                        if(postReturnStatus == 100000001)
                        {
                            returnTransactionHandler.AdjustProductQuantity(postImageEntity, "postTransaction");
                        }

                        //status set to cancelled
                        else if (postReturnStatus == 100000002)
                        {
                            returnTransactionHandler.AdjustProductQuantity(postImageEntity, "cancel");
                        }
                    }

                    if (preVrStatus != postVrStatus)
                    {
                        returnTransactionHandler.ReplicateVrStatus(postImageEntity);
                    }
                   
                }
                catch (Exception ex)
                {
                    //throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace, Environment.NewLine, error));
                    throw new InvalidPluginExecutionException(ex.Message);
                }

            }
        }
    }
}
