// <copyright file="PostSalesDocumentUpdate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>10/4/2016 5:14:49 PM</date>
// <summary>Implements the PostSalesDocumentUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.SalesDocument;

    /// <summary>
    /// PostSalesDocumentUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostSalesDocumentUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// </summary>
        private readonly string preImageAlias = "PreImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostSalesDocumentUpdate"/> class.
        /// </summary>
        public PostSalesDocumentUpdate()
            : base(typeof(PostSalesDocumentUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_sls_salesdocument", new Action<LocalPluginContext>(ExecutePostSalesDocumentUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostSalesDocumentUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;

            try
            {
                bool preApply = preImageEntity.GetAttributeValue<bool>("gsc_apply");
                decimal preAppliedAmount = preImageEntity.Contains("gsc_appliedamount") ? preImageEntity.GetAttributeValue<Money>("gsc_appliedamount").Value
                    : 0;

                bool postApply = postImageEntity.GetAttributeValue<bool>("gsc_apply");
                decimal postAppliedAmount = postImageEntity.Contains("gsc_appliedamount") ? postImageEntity.GetAttributeValue<Money>("gsc_appliedamount").Value
                    : 0;

                SalesDocumentHandler salesDocumentHandler = new SalesDocumentHandler(service, trace);

                //execute if apply was changed
                if (preApply != postApply)
                {
                    
                    //apply document
                    if (postApply == true)
                    {

                        salesDocumentHandler.ApplyCashReceipt(postImageEntity);
                    }
                    //unapply document
                    else
                    {
                        salesDocumentHandler.UnapplyCashReceipt(postImageEntity);
                        service.Delete(postImageEntity.LogicalName, postImageEntity.Id);
                    }
                }

                //execute if applied amount was changed AND apply set to true
                if (preAppliedAmount != postAppliedAmount && postApply == true)
                {
                    salesDocumentHandler.ApplyCashReceipt(postImageEntity);
                }

            }
            catch (Exception ex)
            {
                //throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace, Environment.NewLine, error));
                throw new InvalidPluginExecutionException(ex.Message);
            }
        }
    }
}
