// <copyright file="PostQuoteDiscountCreate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>3/14/2016 11:30:01 AM</date>
// <summary>Implements the PostQuoteDiscountCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.QuoteDiscount;
    using GSC.Rover.DMS.BusinessLogic.Common;
    using Microsoft.Xrm.Sdk.Query;

    /// <summary>
    /// PostQuoteDiscountCreate Plugin.
    /// </summary>    
    public class PostQuoteDiscountCreate: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostQuoteDiscountCreate"/> class.
        /// </summary>
        public PostQuoteDiscountCreate()
            : base(typeof(PostQuoteDiscountCreate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Create", "gsc_cmn_quotediscount", new Action<LocalPluginContext>(ExecutePostQuoteDiscountCreate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostQuoteDiscountCreate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            Entity quoteDiscountEntity = (Entity)context.InputParameters["Target"];

            string message = context.MessageName;

            try
            {
                QuoteDiscountHandler quoteDiscountHandler = new QuoteDiscountHandler(service, trace);

                EntityCollection quoteDiscountCollection = CommonHandler.RetrieveRecordsByOneValue("gsc_cmn_quotediscount", "gsc_cmn_quotediscountid", quoteDiscountEntity.Id, service,
                    null, OrderType.Ascending, new[] {"gsc_discountamount", "gsc_quoteid"});

                if (quoteDiscountCollection.Entities.Count > 0)
                {
                    quoteDiscountHandler.SetQuoteTotalDiscountAmount(quoteDiscountCollection.Entities[0], message);
                }
            }
            catch (Exception ex)
            {
                throw new InvalidPluginExecutionException(String.Concat(ex.Message));
            }
        }
    }
}
