// <copyright file="PostTransactedVehicleUpdate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>12/8/2016 4:34:13 PM</date>
// <summary>Implements the PostTransactedVehicleUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.TransactedVehicle;

    /// <summary>
    /// PostTransactedVehicleUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostTransactedVehicleUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// No Attributes
        /// </summary>
        private readonly string preImageAlias = "preImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// No Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "postImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostTransactedVehicleUpdate"/> class.
        /// </summary>
        public PostTransactedVehicleUpdate()
            : base(typeof(PostTransactedVehicleUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_cmn_transactedvehicle", new Action<LocalPluginContext>(ExecutePostTransactedVehicleUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostTransactedVehicleUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            
            if (!(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)) { return; }

            if (postImageEntity.LogicalName != "gsc_cmn_transactedvehicle") { return; }
            Entity contactEntity = (Entity)context.InputParameters["Target"];

            string message = context.MessageName;

            if (context.Mode == 0) //Synchronous plugin
            {
                try
                {
                    TransactedVehicleHandler transferHandler = new TransactedVehicleHandler(service, trace);

                    Guid preImageToAccount = preImageEntity.GetAttributeValue<EntityReference>("gsc_transfertocorporate") != null
                        ? preImageEntity.GetAttributeValue<EntityReference>("gsc_transfertocorporate").Id
                        : Guid.Empty;

                    Guid preImageToContact = preImageEntity.GetAttributeValue<EntityReference>("gsc_transfertoindividual") != null
                        ? preImageEntity.GetAttributeValue<EntityReference>("gsc_transfertoindividual").Id
                        : Guid.Empty;

                    Guid postImageToAccount = postImageEntity.GetAttributeValue<EntityReference>("gsc_transfertocorporate") != null
                        ? postImageEntity.GetAttributeValue<EntityReference>("gsc_transfertocorporate").Id
                        : Guid.Empty;

                    Guid postImageToContact = postImageEntity.GetAttributeValue<EntityReference>("gsc_transfertoindividual") != null
                        ? postImageEntity.GetAttributeValue<EntityReference>("gsc_transfertoindividual").Id
                        : Guid.Empty;

                    if (preImageToAccount != postImageToAccount)
                    {
                        transferHandler.TransferVehicleOwnership(postImageEntity, "account");
                        transferHandler.CreateTransferHistory(postImageEntity, "account");
                    }

                    if (preImageToContact != postImageToContact)
                    {
                        transferHandler.TransferVehicleOwnership(postImageEntity, "contact");
                        transferHandler.CreateTransferHistory(postImageEntity, "contact");
                    }

                }
                catch (Exception ex)
                {
                    //throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace, Environment.NewLine, error));
                    throw new InvalidPluginExecutionException(ex.Message);
                }
            }
        }
    }
}
