// <copyright file="PostVehicleCountEntryDetailsUpdate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>9/2/2016 2:21:31 PM</date>
// <summary>Implements the PostVehicleCountEntryDetailsUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.VehicleCountEntryDetail;

    /// <summary>
    /// PostVehicleCountEntryDetailsUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostVehicleCountEntryDetailsUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// No Attributes
        /// </summary>
        private readonly string preImageAlias = "preImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// No Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "postImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostVehicleCountEntryDetailsUpdate"/> class.
        /// </summary>
        public PostVehicleCountEntryDetailsUpdate()
            : base(typeof(PostVehicleCountEntryDetailsUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_iv_vehiclecountentrydetails", new Action<LocalPluginContext>(ExecutePostVehicleCountEntryDetailsUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostVehicleCountEntryDetailsUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            Entity countEntryDetail = (Entity)context.InputParameters["Target"];

            if (!(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)) { return; }

            if (countEntryDetail.LogicalName != "gsc_iv_vehiclecountentrydetails") { return; }

            if (context.Mode == 0) //Synchronous Plug-in
            {
                string message = context.MessageName;

                try
                {
                    VehicleCountEntryDetailHandler vehicleCountHandler = new VehicleCountEntryDetailHandler(service, trace);

                    var preImageCountedQty = preImageEntity.Contains("gsc_countedqty")
                        ? preImageEntity.GetAttributeValue<Int32>("gsc_countedqty")
                        : 0;
                    var preImageBreakdownCount = preImageEntity.Contains("gsc_breakdowncount")
                        ? preImageEntity.GetAttributeValue<String>("gsc_breakdowncount")
                        : String.Empty;

                    var postImageCountedQty = postImageEntity.Contains("gsc_countedqty")
                        ? postImageEntity.GetAttributeValue<Int32>("gsc_countedqty")
                        : 0;
                    var postImageBreakdownCount = postImageEntity.Contains("gsc_breakdowncount")
                        ? postImageEntity.GetAttributeValue<String>("gsc_breakdowncount")
                        : String.Empty;

                    if (preImageCountedQty != postImageCountedQty)
                    {
                        vehicleCountHandler.ComputeVariance(postImageEntity);
                        vehicleCountHandler.UpdateStatus(postImageEntity);

                        if (postImageEntity.Contains("gsc_verifiedcountedqty") && postImageEntity.GetAttributeValue<Int32>("gsc_verifiedcountedqty") != 0)
                        {
                            vehicleCountHandler.ComputeVerifiedCountedQty(postImageEntity);
                        }
                    }

                    if (preImageBreakdownCount != postImageBreakdownCount)
                    {
                        vehicleCountHandler.ComputeVerifiedCountedQty(postImageEntity);
                    }
                }
                catch (Exception ex)
                {
                    throw new InvalidPluginExecutionException(String.Concat(ex.Message));
                }
            }
        }
    }
}
