// <copyright file="PostVehiclePurchaseOrderDetailCreate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>7/12/2016 4:52:19 PM</date>
// <summary>Implements the PostVehiclePurchaseOrderDetailCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.VehiclePurchaseOrderDetails;
    using GSC.Rover.DMS.BusinessLogic.VehiclePurchaseOrder;
    using GSC.Rover.DMS.BusinessLogic.Common;
    using Microsoft.Xrm.Sdk.Query;

    /// <summary>
    /// PostVehiclePurchaseOrderDetailCreate Plugin.
    /// </summary>    
    public class PostVehiclePurchaseOrderDetailCreate: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostVehiclePurchaseOrderDetailCreate"/> class.
        /// </summary>
        public PostVehiclePurchaseOrderDetailCreate()
            : base(typeof(PostVehiclePurchaseOrderDetailCreate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Create", "gsc_cmn_purchaseorderitemdetails", new Action<LocalPluginContext>(ExecutePostVehiclePurchaseOrderDetailCreate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostVehiclePurchaseOrderDetailCreate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            Entity vpoDetails = (Entity)context.InputParameters["Target"];

            string message = context.MessageName;
            string error = "";

            try
            {
                VehiclePurchaseOrderDetailsHandler vpoDetailsHandler = new VehiclePurchaseOrderDetailsHandler(service, trace);
                VehiclePurchaseOrderHandler vpoHandler = new VehiclePurchaseOrderHandler(service, trace);

                EntityCollection vpoDetailsCollection = CommonHandler.RetrieveRecordsByOneValue("gsc_cmn_purchaseorderitemdetails", "gsc_cmn_purchaseorderitemdetailsid", vpoDetails.Id, service, null, OrderType.Ascending,
                    new[] { "gsc_productid", "gsc_dnpamount", "gsc_purchaseorderid", "gsc_branchid" });
                if (vpoDetailsCollection != null && vpoDetailsCollection.Entities.Count > 0)
                {
                    
                    Entity vpoDetailsToUpdate = vpoDetailsCollection.Entities[0];
                    vpoDetailsHandler.SetDNPAmount(vpoDetailsToUpdate);
                }
            }

            catch (Exception ex)
            {
                throw new InvalidPluginExecutionException(ex.Message);
                //throw new InvalidPluginExecutionException(String.Concat("(Exceptionss)\n", ex.Message, Environment.NewLine, ex.StackTrace, Environment.NewLine, "trace>>>" + error));
            }
        }
    }
}
