// <copyright file="PostReceivingTransactionUpdate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>7/12/2016 2:09:34 PM</date>
// <summary>Implements the PostReceivingTransactionUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.ReceivingTransaction;
    using GSC.Rover.DMS.BusinessLogic.Common;
    using Microsoft.Xrm.Sdk.Query;
    using GSC.Rover.DMS.BusinessLogic.InventoryMovement;

    /// <summary>
    /// PostReceivingTransactionUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostReceivingTransactionUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// </summary>
        private readonly string preImageAlias = "PreImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostReceivingTransactionUpdate"/> class.
        /// </summary>
        public PostReceivingTransactionUpdate()
            : base(typeof(PostReceivingTransactionUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_cmn_receivingtransaction", new Action<LocalPluginContext>(ExecutePostReceivingTransactionUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostReceivingTransactionUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            Entity receivingTransactionEntity = (Entity)context.InputParameters["Target"];

            if (!(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)) { return; }

            if (receivingTransactionEntity.LogicalName != "gsc_cmn_receivingtransaction") { return; }

            if (context.Mode == 0) //Synchronous Plug-in
            {
                string message = context.MessageName;

                try
                {
                    #region Pre-images
                    var preImageReceivingStatus = preImageEntity.Contains("gsc_receivingstatus")
                        ? preImageEntity.GetAttributeValue<OptionSetValue>("gsc_receivingstatus").Value
                        : 0;
                    var preImageWBNo = preImageEntity.Contains("gsc_warrantybookletno")
                        ? preImageEntity.GetAttributeValue<String>("gsc_warrantybookletno")
                        : String.Empty;

                    #endregion

                    #region Post-images
                    var postImageReceivingStatus = postImageEntity.Contains("gsc_receivingstatus")
                        ? postImageEntity.GetAttributeValue<OptionSetValue>("gsc_receivingstatus").Value
                        : 0;
                    var postImageWBNo = postImageEntity.Contains("gsc_warrantybookletno")
                        ? postImageEntity.GetAttributeValue<String>("gsc_warrantybookletno")
                        : String.Empty;

                    #endregion

                    ReceivingTransactionHandler receivingTransactionHandler = new ReceivingTransactionHandler(service, trace);

                    if (preImageWBNo != postImageWBNo)
                    {
                        receivingTransactionHandler.IsWBNoUnique(postImageEntity);
                        receivingTransactionHandler.UpdateInventoryWBNo(postImageEntity);
                    }

                    if (preImageReceivingStatus != postImageReceivingStatus)
                    {
                        receivingTransactionHandler.UpdatePOItem(postImageEntity);
                        receivingTransactionHandler.UpdateVPOSatus(postImageEntity);
                        receivingTransactionHandler.SubtractinUnservedPO(postImageEntity);
                        receivingTransactionHandler.InventoryMovementUponReceiving(postImageEntity);

                        if (postImageReceivingStatus == 100000000)
                        {
                            if (receivingTransactionHandler.IsAllocatedVehicle(postImageEntity) == true)
                            {
                                postImageEntity["gsc_receivingstatus"] = new OptionSetValue(100000003);
                                throw new InvalidPluginExecutionException("Vehicle is currently allocated, remove the allocation to cancel the record.");
                            }
                            receivingTransactionHandler.CancelReceivingTransaction(postImageEntity);
                        }

                        if (postImageReceivingStatus == 100000003 || postImageReceivingStatus == 100000004)
                        {
                            receivingTransactionHandler.UpdateVPOSatusinVPO(postImageEntity);
                        }
                    }
                }
                catch (Exception ex)
                {
                    //if (ex.Message.Contains("Vehicle is currently allocated, remove the allocation to cancel the record."))
                        throw new InvalidPluginExecutionException(ex.Message);
                   // else
                   // throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace));
                }
            }
        }
    }
}
