// <copyright file="PostRequirementChecklistUpdate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>10/6/2016 6:37:00 PM</date>
// <summary>Implements the PostRequirementChecklistUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.RequirementChecklist;

    /// <summary>
    /// PostRequirementChecklistUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostRequirementChecklistUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// </summary>
        private readonly string preImageAlias = "PreImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostRequirementChecklistUpdate"/> class.
        /// </summary>
        public PostRequirementChecklistUpdate()
            : base(typeof(PostRequirementChecklistUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_sls_requirementchecklist", new Action<LocalPluginContext>(ExecutePostRequirementChecklistUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostRequirementChecklistUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;

            if (!(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)) { return; }

            Entity requirementChecklistEntity = (Entity)context.InputParameters["Target"];

            if (requirementChecklistEntity.LogicalName != "gsc_sls_requirementchecklist") { return; }

            if (context.Mode == 0) //synchronous plugin
            {
                try
                {
                    string message = context.MessageName;

                    RequirementChecklistHandler requirementChecklistHandler = new RequirementChecklistHandler(service, trace);

                    var preImageSubmitted = preImageEntity.Contains("gsc_submitted")
                        ? preImageEntity.GetAttributeValue<bool>("gsc_submitted")
                        : false;
                    var preImageDocumentType = preImageEntity.Contains("gsc_documenttype")
                        ? preImageEntity.GetAttributeValue<bool>("gsc_documenttype")
                        : false;
                    var preImageDocumentName = preImageEntity.Contains("gsc_documentchecklistid")
                        ? preImageEntity.GetAttributeValue<EntityReference>("gsc_documentchecklistid").Id
                        : Guid.Empty;


                    var postImageSubmitted = postImageEntity.Contains("gsc_submitted")
                        ? postImageEntity.GetAttributeValue<bool>("gsc_submitted")
                        : false;
                    var postImageDocumentType = postImageEntity.Contains("gsc_documenttype")
                        ? postImageEntity.GetAttributeValue<bool>("gsc_documenttype")
                        : false;
                    var postImageDocumentName = postImageEntity.Contains("gsc_documentchecklistid") ?
                        postImageEntity.GetAttributeValue<EntityReference>("gsc_documentchecklistid").Id
                        : Guid.Empty;

                    if (preImageSubmitted != postImageSubmitted && postImageSubmitted == true)
                    {
                        requirementChecklistHandler.SetForAllocation(postImageEntity);
                    }

                    if (preImageDocumentType != postImageDocumentType || preImageDocumentName != postImageDocumentName)
                    {
                        requirementChecklistHandler.ValidateEdit(postImageEntity);
                    }
                }

                catch (Exception ex)
                {
                    if (ex.Message.Contains("Unable to modify documents from bank."))
                        throw new InvalidPluginExecutionException("Unable to modify documents from bank.");
                    else
                        throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace));
                }
            }
        }
    }
}
