// <copyright file="PostVehicleCountScheduleUpdate.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>8/24/2016 1:27:03 PM</date>
// <summary>Implements the PostVehicleCountScheduleUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using DMS.BusinessLogic.VehicleCountSchedule;

    /// <summary>
    /// PostVehicleCountScheduleUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// All Attributes
    /// </summary>    
    public class PostVehicleCountScheduleUpdate: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// No Attributes
        /// </summary>
        private readonly string preImageAlias = "preImage";

        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// No Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "postImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostVehicleCountScheduleUpdate"/> class.
        /// </summary>
        public PostVehicleCountScheduleUpdate()
            : base(typeof(PostVehicleCountScheduleUpdate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Update", "gsc_iv_vehiclecountschedule", new Action<LocalPluginContext>(ExecutePostVehicleCountScheduleUpdate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostVehicleCountScheduleUpdate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity preImageEntity = (context.PreEntityImages != null && context.PreEntityImages.Contains(this.preImageAlias)) ? context.PreEntityImages[this.preImageAlias] : null;
            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            Entity vehicleCount = (Entity)context.InputParameters["Target"];

            if (!(context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)) { return; }

            if (vehicleCount.LogicalName != "gsc_iv_vehiclecountschedule") { return; }

            if (context.Mode == 0) //Synchronous Plug-in
            {
                string message = context.MessageName;

                try
                {
                    #region Pre-images
                    Guid preImageSite = preImageEntity.GetAttributeValue<EntityReference>("gsc_siteid") != null
                        ? preImageEntity.GetAttributeValue<EntityReference>("gsc_siteid").Id
                        : Guid.Empty;
                    
                    Guid preImageBaseModel = preImageEntity.GetAttributeValue<EntityReference>("gsc_vehiclebasemodelid") != null
                        ? preImageEntity.GetAttributeValue<EntityReference>("gsc_vehiclebasemodelid").Id
                        : Guid.Empty;
                    
                    Guid preImageProduct = preImageEntity.GetAttributeValue<EntityReference>("gsc_productid") != null
                        ? preImageEntity.GetAttributeValue<EntityReference>("gsc_productid").Id
                        : Guid.Empty;
                    
                    Guid preImageColor = preImageEntity.GetAttributeValue<EntityReference>("gsc_vehiclecolorid") != null
                        ? preImageEntity.GetAttributeValue<EntityReference>("gsc_vehiclecolorid").Id
                        : Guid.Empty;
                    
                    String preImageModel = preImageEntity.Contains("gsc_modelcode") 
                        ? preImageEntity.GetAttributeValue<String>("gsc_modelcode")
                        : String.Empty;
                    
                    String preImageOption = preImageEntity.Contains("gsc_optioncode") 
                        ? preImageEntity.GetAttributeValue<String>("gsc_optioncode")
                        : String.Empty;

                    String preImageCopyFilterResult = preImageEntity.Contains("gsc_copyfilterresult")
                        ? preImageEntity.GetAttributeValue<String>("gsc_copyfilterresult")
                        : String.Empty;

                    String preImageCopyAllFilterResult = preImageEntity.Contains("gsc_copyallfilterresult")
                        ? preImageEntity.GetAttributeValue<String>("gsc_copyallfilterresult")
                        : String.Empty;

                    String preImageClearFilterResult = preImageEntity.Contains("gsc_clearfilterresult")
                        ? preImageEntity.GetAttributeValue<String>("gsc_clearfilterresult")
                        : String.Empty;

                    String preImageClearDetail = preImageEntity.Contains("gsc_cleardetail")
                        ? preImageEntity.GetAttributeValue<String>("gsc_cleardetail")
                        : String.Empty;

                    var preImageChangeStatus = preImageEntity.Contains("gsc_changestatus")
                        ? preImageEntity.GetAttributeValue<OptionSetValue>("gsc_changestatus").Value
                        : 0;

                    var preImageReuseCount = preImageEntity.Contains("gsc_reusecount")
                        ? preImageEntity.GetAttributeValue<String>("gsc_reusecount")
                        : String.Empty;
                    #endregion

                    #region Post-images
                    Guid postImageSite = postImageEntity.GetAttributeValue<EntityReference>("gsc_siteid") != null
                        ? postImageEntity.GetAttributeValue<EntityReference>("gsc_siteid").Id
                        : Guid.Empty;
                    
                    Guid postImageBaseModel = postImageEntity.GetAttributeValue<EntityReference>("gsc_vehiclebasemodelid") != null
                        ? postImageEntity.GetAttributeValue<EntityReference>("gsc_vehiclebasemodelid").Id
                        : Guid.Empty;
                    
                    Guid postImageProduct = postImageEntity.GetAttributeValue<EntityReference>("gsc_productid") != null
                        ? postImageEntity.GetAttributeValue<EntityReference>("gsc_productid").Id
                        : Guid.Empty;
                    
                    Guid postImageColor = postImageEntity.GetAttributeValue<EntityReference>("gsc_vehiclecolorid") != null
                        ? postImageEntity.GetAttributeValue<EntityReference>("gsc_vehiclecolorid").Id
                        : Guid.Empty;
                    
                    String postImageModel = postImageEntity.Contains("gsc_modelcode") 
                        ? postImageEntity.GetAttributeValue<String>("gsc_modelcode")
                        : String.Empty;
                    
                    String postImageOption = postImageEntity.Contains("gsc_optioncode") 
                        ? postImageEntity.GetAttributeValue<String>("gsc_optioncode")
                        : String.Empty;

                    String postImageCopyFilterResult = postImageEntity.Contains("gsc_copyfilterresult")
                        ? postImageEntity.GetAttributeValue<String>("gsc_copyfilterresult")
                        : String.Empty;

                    String postImageCopyAllFilterResult = postImageEntity.Contains("gsc_copyallfilterresult")
                        ? postImageEntity.GetAttributeValue<String>("gsc_copyallfilterresult")
                        : String.Empty;

                    String postImageClearFilterResult = postImageEntity.Contains("gsc_clearfilterresult")
                        ? postImageEntity.GetAttributeValue<String>("gsc_clearfilterresult")
                        : String.Empty;

                    String postImageClearDetail = postImageEntity.Contains("gsc_cleardetail")
                        ? postImageEntity.GetAttributeValue<String>("gsc_cleardetail")
                        : String.Empty;

                    var postImageChangeStatus = postImageEntity.Contains("gsc_changestatus")
                        ? postImageEntity.GetAttributeValue<OptionSetValue>("gsc_changestatus").Value
                        : 0;

                    var postImageReuseCount = postImageEntity.Contains("gsc_reusecount")
                        ? postImageEntity.GetAttributeValue<String>("gsc_reusecount")
                        : String.Empty;
                    #endregion

                    VehicleCountScheduleHandler vehicleCountHandler = new VehicleCountScheduleHandler(service, trace);

                    //Functions on Invoice No change
                    if (preImageSite != postImageSite || preImageBaseModel !=  postImageBaseModel || preImageProduct != postImageProduct ||
                    preImageColor != postImageColor || preImageModel != postImageModel || preImageOption != postImageOption)
                    {
                        vehicleCountHandler.ApplyFilter(postImageEntity);
                    }

                    if (preImageCopyFilterResult != postImageCopyFilterResult)
                    {
                        vehicleCountHandler.ReplicateFilterResult(postImageEntity);
                    }

                    if (preImageCopyAllFilterResult != postImageCopyAllFilterResult)
                    {
                        vehicleCountHandler.ReplicateAllFilterResult(postImageEntity);
                    }

                    if (preImageClearFilterResult != postImageClearFilterResult)
                    {
                        vehicleCountHandler.ClearFilterResults(postImageEntity);
                    }

                    if (preImageClearDetail != postImageClearDetail)
                    {
                        vehicleCountHandler.ClearVehicleForCounting(postImageEntity);
                    }

                    if (preImageChangeStatus != postImageChangeStatus)
                    {
                        if (postImageChangeStatus == 100000001) 
                         {
                           vehicleCountHandler.CheckDuplicateStartedSchedule(postImageEntity);
                         }

                        else if (postImageChangeStatus == 100000000)
                         {
                             vehicleCountHandler.CancelCountSchedule(postImageEntity);
                         }
                    }

                    if (preImageReuseCount != postImageReuseCount)
                    {
                        vehicleCountHandler.ReuseCountSchedule(postImageEntity);
                    }

                }
                catch (Exception ex)
                {
                    throw new InvalidPluginExecutionException(String.Concat(ex.Message));
                }
            }
        }
    }
}
