// <copyright file="PreValidateOrderCabChassisDelete.cs" company="">
// Copyright (c) 2017 All Rights Reserved
// </copyright>
// <author></author>
// <date>4/10/2017 1:47:37 PM</date>
// <summary>Implements the PreValidateOrderCabChassisDelete Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.SalesOrderCabChassis;
    using GSC.Rover.DMS.BusinessLogic.Common;
    using Microsoft.Xrm.Sdk.Query;

    /// <summary>
    /// PreValidateOrderCabChassisDelete Plugin.
    /// </summary>    
    public class PreValidateOrderCabChassisDelete: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidateOrderCabChassisDelete"/> class.
        /// </summary>
        public PreValidateOrderCabChassisDelete()
            : base(typeof(PreValidateOrderCabChassisDelete))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(10, "Delete", "gsc_sls_ordercabchassis", new Action<LocalPluginContext>(ExecutePreValidateOrderCabChassisDelete)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePreValidateOrderCabChassisDelete(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            var orderCabChassisEntity = (EntityReference)context.InputParameters["Target"];
            string message = context.MessageName;
            string error = "";

            try
            {
                SalesOrderCabChassisHandler orderCabChassisHandler = new SalesOrderCabChassisHandler(service, trace);

                EntityCollection orderCabChassisCollection = CommonHandler.RetrieveRecordsByOneValue("gsc_sls_ordercabchassis", "gsc_sls_ordercabchassisid", orderCabChassisEntity.Id, service, null, OrderType.Ascending,
                    new[] { "gsc_orderid", "gsc_amount", "gsc_financing" });

                if (orderCabChassisCollection != null && orderCabChassisCollection.Entities.Count > 0)
                {
                    Entity orderCabChassis = orderCabChassisCollection.Entities[0];
                    orderCabChassisHandler.SetCCAddOnAmount(orderCabChassis, message);
                }

            }
            catch (Exception ex)
            {
                throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace, Environment.NewLine, error));
            }
        }
    }
}
