// <copyright file="PreValidateDocumentChecklistDelete.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>10/6/2016 5:49:14 PM</date>
// <summary>Implements the PreValidateDocumentChecklistDelete Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.DocumentChecklist;
    using GSC.Rover.DMS.BusinessLogic.Common;
    using Microsoft.Xrm.Sdk.Query;

    /// <summary>
    /// PreValidateDocumentChecklistDelete Plugin.
    /// </summary>    
    public class PreValidateDocumentChecklistDelete: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidateDocumentChecklistDelete"/> class.
        /// </summary>
        public PreValidateDocumentChecklistDelete()
            : base(typeof(PreValidateDocumentChecklistDelete))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(10, "Delete", "gsc_sls_documentchecklist", new Action<LocalPluginContext>(ExecutePreValidateDocumentChecklistDelete)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePreValidateDocumentChecklistDelete(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;

            var documentChecklistEntity = (EntityReference)context.InputParameters["Target"];
            string message = context.MessageName;


            try
            {
                EntityCollection vehicleSalesReturnCollection = CommonHandler.RetrieveRecordsByOneValue("gsc_sls_documentchecklist", "gsc_sls_documentchecklistid", documentChecklistEntity.Id, service, null, OrderType.Ascending,
                    new[] { "gsc_documentchecklistpn" });


                DocumentChecklistHandler documentChecklistHandler = new DocumentChecklistHandler(service, trace);
                if (documentChecklistHandler.ValidateDelete(vehicleSalesReturnCollection.Entities[0]))
                    throw new InvalidPluginExecutionException("You cannot delete a pre-defined document in this list.");
            }
            catch (Exception ex)
            {
                throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace));
            }
        }
    }
}
