// <copyright file="PreValidateProspectInquiryDelete.cs" company="">
// Copyright (c) 2017 All Rights Reserved
// </copyright>
// <author></author>
// <date>4/3/2017 1:42:28 PM</date>
// <summary>Implements the PreValidateProspectInquiryDelete Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;

    using GSC.Rover.DMS.BusinessLogic.Common;
    using GSC.Rover.DMS.BusinessLogic.ProspectInquiry;
    using Microsoft.Xrm.Sdk.Query;    

    /// <summary>
    /// PreValidateProspectInquiryDelete Plugin.
    /// </summary>    
    public class PreValidateProspectInquiryDelete: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidateProspectInquiryDelete"/> class.
        /// </summary>
        public PreValidateProspectInquiryDelete()
            : base(typeof(PreValidateProspectInquiryDelete))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(10, "Delete", "lead", new Action<LocalPluginContext>(ExecutePreValidateProspectInquiryDelete)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePreValidateProspectInquiryDelete(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            var prospectInquiryId = (EntityReference)context.InputParameters["Target"];

            try
            {
                EntityCollection prospectInquiryRecords = CommonHandler.RetrieveRecordsByOneValue("lead", "leadid", prospectInquiryId.Id, service,
                    null, OrderType.Ascending, new[] { "leadid", "statecode" });

                if (prospectInquiryRecords != null && prospectInquiryRecords.Entities.Count > 0)
                {
                    ProspectInquiryHandler prospectInquiryHandler = new ProspectInquiryHandler(service, trace);
                    prospectInquiryHandler.RestrictProspectInquiryDelete(prospectInquiryRecords.Entities[0]);
                }                
            }

            catch (Exception ex)
            {
                throw new InvalidPluginExecutionException(ex.Message);
            }
        }
    }
}
