// <copyright file="PreValidateReturnTransactionDelete.cs" company="">
// Copyright (c) 2017 All Rights Reserved
// </copyright>
// <author></author>
// <date>2/8/2017 2:21:33 PM</date>
// <summary>Implements the PreValidateReturnTransactionDelete Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.Common;
    using GSC.Rover.DMS.BusinessLogic.ReturnTransaction;
    using Microsoft.Xrm.Sdk.Query;

    /// <summary>
    /// PreValidateReturnTransactionDelete Plugin.
    /// </summary>    
    public class PreValidateReturnTransactionDelete: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidateReturnTransactionDelete"/> class.
        /// </summary>
        public PreValidateReturnTransactionDelete()
            : base(typeof(PreValidateReturnTransactionDelete))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(10, "Delete", "gsc_cmn_returntransaction", new Action<LocalPluginContext>(ExecutePreValidateReturnTransactionDelete)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePreValidateReturnTransactionDelete(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            var returnTransaction = (EntityReference)context.InputParameters["Target"];

            try
            {
               

                EntityCollection returnTransactionCollection = CommonHandler.RetrieveRecordsByOneValue("gsc_cmn_returntransaction", "gsc_cmn_returntransactionid", returnTransaction.Id, service,
                    null, OrderType.Ascending, new[] { "gsc_cmn_returntransactionid", "gsc_receivingtransactionid","gsc_returnstatus" });
                

                if (returnTransactionCollection.Entities.Count > 0)
                {
                    ReturnTransactionHandler returnTransactionHandler = new ReturnTransactionHandler(service, trace);
                    Entity returnTransactionEntity = returnTransactionCollection.Entities[0];

                    if (returnTransactionHandler.IsValidToDelete(returnTransactionEntity) == false)
                        throw new InvalidPluginExecutionException("Unable to delete return transaction record(s). Only record with open status can be deleted.");
                    returnTransactionHandler.AdjustProductQuantity(returnTransactionEntity, "cancel");                   
                }
            }

            catch (Exception ex)
            {
                if (ex.Message.Contains("Unable to delete return transaction record(s). Only record with open status can be deleted."))
                    throw new InvalidPluginExecutionException(ex.Message);
                else
                    throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace, Environment.NewLine));
            }

        }
    }
}
