// <copyright file="PreValidateQuoteChargeDelete.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>3/14/2016 2:52:40 PM</date>
// <summary>Implements the PreValidateQuoteChargeDelete Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.QuoteCharge;
    using GSC.Rover.DMS.BusinessLogic.Common;
    using Microsoft.Xrm.Sdk.Query;

    /// <summary>
    /// PreValidateQuoteChargeDelete Plugin.
    /// </summary>    
    public class PreValidateQuoteChargeDelete: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidateQuoteChargeDelete"/> class.
        /// </summary>
        public PreValidateQuoteChargeDelete()
            : base(typeof(PreValidateQuoteChargeDelete))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(10, "Delete", "gsc_cmn_quotecharge", new Action<LocalPluginContext>(ExecutePreValidateQuoteChargeDelete)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePreValidateQuoteChargeDelete(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            var quoteChargeEntity = (EntityReference)context.InputParameters["Target"];
            string message = context.MessageName;
            string error = "";

            if (context.Depth > 1) { return; }

            try
            {
                QuoteChargeHandler quoteChargeHandler = new QuoteChargeHandler(service, trace);

                #region Calling SetQuoteTotalChargesAmount method

                EntityCollection quoteChargeRecords = CommonHandler.RetrieveRecordsByOneValue("gsc_cmn_quotecharge", "gsc_cmn_quotechargeid", quoteChargeEntity.Id, service, null, OrderType.Ascending,
                    new[] { "gsc_quoteid", "gsc_chargeamount", "gsc_chargetype", "gsc_actualcost" });

                if (quoteChargeRecords != null && quoteChargeRecords.Entities.Count > 0)
                {
                    Entity quoteCharge = quoteChargeRecords.Entities[0];
                    quoteChargeHandler.SetQuoteTotalChargesAmount(quoteCharge, message);
                }

                #endregion
            }
            catch (Exception ex)
            {
                throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace, Environment.NewLine, error));
            }
        }
    }
}
