// <copyright file="PreValidateVehicleInTransitTransferDelete.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>8/25/2016 2:51:26 PM</date>
// <summary>Implements the PreValidateVehicleInTransitTransferDelete Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.Common;
    using GSC.Rover.DMS.BusinessLogic.VehicleInTransitTransfer;
    using Microsoft.Xrm.Sdk.Query;

    /// <summary>
    /// PreValidateVehicleInTransitTransferDelete Plugin.
    /// </summary>    
    public class PreValidateVehicleInTransitTransferDelete: Plugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidateVehicleInTransitTransferDelete"/> class.
        /// </summary>
        public PreValidateVehicleInTransitTransferDelete()
            : base(typeof(PreValidateVehicleInTransitTransferDelete))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(10, "Delete", "gsc_iv_vehicleintransittransfer", new Action<LocalPluginContext>(ExecutePreValidateVehicleInTransitTransferDelete)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePreValidateVehicleInTransitTransferDelete(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            var vehicleInTransit = (EntityReference)context.InputParameters["Target"];
            string message = context.MessageName;

            if (context.Depth > 1) { return; }

            try
            {
                EntityCollection vehicleInTransitCollection = CommonHandler.RetrieveRecordsByOneValue("gsc_iv_vehicleintransittransfer", "gsc_iv_vehicleintransittransferid", vehicleInTransit.Id, service,
                    null, OrderType.Ascending, new[] { "gsc_intransittransferstatus" });

                VehicleInTransitTransferHandler vehicleInTransitHandler = new VehicleInTransitTransferHandler(service, trace);
                vehicleInTransitHandler.ValidateTransaction(vehicleInTransitCollection.Entities[0], message);
            }

            catch (Exception ex)
            {
                if (ex.Message.Contains("Unable to delete Shipped Vehicle In-Transit Transfer record."))
                    throw new InvalidPluginExecutionException("Unable to delete Shipped Vehicle In-Transit Transfer record.");
                else
                    throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace));
            }
        }
    }
}
