// <copyright file="PreValidateVehicleSalesReturnDelete.cs" company="">
// Copyright (c) 2016 All Rights Reserved
// </copyright>
// <author></author>
// <date>6/3/2016 7:02:16 PM</date>
// <summary>Implements the PreValidateVehicleSalesReturnDelete Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace GSC.Rover.DMS.Platform.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using GSC.Rover.DMS.BusinessLogic.Common;
    using GSC.Rover.DMS.BusinessLogic.VehicleSalesReturn;
    using Microsoft.Xrm.Sdk.Query;

    /// <summary>
    /// PreValidateVehicleSalesReturnDelete Plugin.
    /// </summary>    
    public class PreValidateVehicleSalesReturnDelete: Plugin
    {
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes before the core platform operation executes.
        /// The image contains the following attributes:
        /// All Attributes
        /// </summary>
        private readonly string preImageAlias = "PreImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidateVehicleSalesReturnDelete"/> class.
        /// </summary>
        public PreValidateVehicleSalesReturnDelete()
            : base(typeof(PreValidateVehicleSalesReturnDelete))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(10, "Delete", "gsc_sls_vehiclesalesreturn", new Action<LocalPluginContext>(ExecutePreValidateVehicleSalesReturnDelete)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePreValidateVehicleSalesReturnDelete(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            IPluginExecutionContext context = localContext.PluginExecutionContext;
            IOrganizationService service = localContext.OrganizationService;
            ITracingService trace = localContext.TracingService;
            var vehicleSalesReturn = (EntityReference)context.InputParameters["Target"];
            string message = context.MessageName;

            if (context.Depth > 1) { return; }

            try
            {
                EntityCollection vehicleSalesReturnCollection = CommonHandler.RetrieveRecordsByOneValue("gsc_sls_vehiclesalesreturn", "gsc_sls_vehiclesalesreturnid", vehicleSalesReturn.Id, service, null, OrderType.Ascending,
                    new[] { "gsc_vehiclesalesreturnstatus" });

                VehicleSalesReturnHandler vehicleSalesReturnHandler = new VehicleSalesReturnHandler(service, trace);
                if (vehicleSalesReturnHandler.isPostedTransaction(vehicleSalesReturnCollection.Entities[0]) == true)
                    throw new InvalidPluginExecutionException("Unable to delete posted sales return.");
            }

            catch (Exception ex)
            {
                if (ex.Message.Contains("Unable to delete posted sales return."))
                    throw new InvalidPluginExecutionException("Unable to delete posted sales return.");
                else
                    throw new InvalidPluginExecutionException(String.Concat("(Exception)\n", ex.Message, Environment.NewLine, ex.StackTrace));
            }
        }
            
    }
}
